# FamilyBot/src/familybot/Token_Sender/config-template.yaml

# --- Token Sender Bot Configuration ---

# REQUIRED: IP address of the main FamilyBot's WebSocket server.
# Use "127.0.0.1" for local development if the bot is running on the same machine.
# If the bot is on a different machine, use its local network IP or public IP.
server_ip: "127.0.0.1"

# REQUIRED: The directory where the Steam webapi_token and its expiration timestamp will be saved.
# We recommend using a relative path like "tokens/" which will resolve to "FamilyBot/tokens/"
# from the project root. The script will attempt to create this directory if it doesn't exist.
token_save_path: "tokens/"

# REQUIRED: The complete path to the Firefox profile you configured for Selenium.
# This profile MUST be logged into Steam.
# Example Windows path: "C:/Users/YourUserName/AppData/Roaming/Mozilla/Firefox/Profiles/your_profile_name"
# Ensure you use forward slashes (/) or escaped backslashes (\\) in the path.
firefox_profile_path: ""

# OPTIONAL: Set to 'true' if you want your computer to shut down after the token is successfully sent.
# This is typically used for dedicated systems that only run this task periodically.
# For development, set this to 'false'.
shutdown: false